### PR TITLE
Fix PostgreSQL problem with given ids

### PR DESCRIPTION
**Pull request by blafasel42**
Postgres Driver will throw an exception when using lastInsertId() when the insert before had a primary key field set. i modified the DBALConnect to just ignore that exception (assignId() will ignore the assign anyway when the id field is already present in $row).

Now this works for me. Hope i did not miss anything.

### CODE REVIEW

**Comment by blafasel42** [comment]
added some fix for sf 5 and replaced faker reference to fakerphp/faker

**Comment by MontealegreLuis** [comment]
Thank you @blafasel42!

I haven't had much time to continue working on this package. If you want to become a maintainer, please let me know.

**Comment by blafasel42** [comment]
Hi @MontealegreLuis ,

why not. I have a fork anyway. Works with sf6 and PHP8 and DBAL 3 now ;)
And it seems i am the only one using the package anyway...

**Comment by MontealegreLuis** [comment]
Awesome! Just sent you an invite @blafasel42.

**Pull request merged**
